import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Stack, Text, useTheme } from "@chakra-ui/react";
import Headline from "@/components/headline";

import DataProvider from "@/components/dataProvider";
import TokenCards from "@/components/tokenCards";
import BridgeExplain from "@/components/bridgeExplain";
import FeaturedTokens from "@/components/featuredTokens";
import PoolExplain from "@/components/poolExplain";
import StartButtonGroup from "@/components/startButtonGroup";

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Tokamak Bridge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box color={"white"}>
        <Stack
          mt={{base:"120px", sm:0}}
          pt={{base:"0px", sm:"150px"}}
          fontFamily={theme.fonts.poppins}
          zIndex={100}
          color={"white"}
          bgImage="url('/assets/background.png')"
          bgPos={"top"}
          bgRepeat={"no-repeat"}
          bgSize={"contain"}
          minH={"100vh"}
        >
          <Headline />

          <Text
            w={["full", 1000, 1000]}
            mx={"auto"}
            pl={[35, 160, 160]}
            pr={[35, 0, 0]}
            mt={{base: 94, sm: 94, md:122}}
            fontSize={[16, 18, 18]}
            fontWeight={400}
            lineHeight={"200%"}
          >
            With it’s fun card game-like interface, fast transaction speeds and
            reward-full ecosystem, crypto enthusiasts will enjoy an all-in-one
            solution for Bridge and Swap functionality.
          </Text>

          <DataProvider />
          <FeaturedTokens />
          <TokenCards />
          <BridgeExplain />
          <PoolExplain />
          <StartButtonGroup />
        </Stack>
      </Box>
    </>
  );
}
