import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Stack, Text, useTheme } from "@chakra-ui/react";
import Headline from "@/components/headline";

import DataProvider from "@/components/dataProvider";
import TokenCards from "@/components/TokenCards";
import BridgeExplain from "@/components/bridgeExplain";
import FeaturedTokens from "@/components/featuredTokens";
import PoolExplain from "@/components/poolExplain";
import StartButtonGroup from "@/components/startButtonGroup";

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Tokamak Bridge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box color={"white"}>
        <Stack
          pt={"220px"}
          fontFamily={theme.fonts.poppins}
          zIndex={100}
          color={"white"}
          bgImage="url('/assets/background.png')"
          bgPos={"top"}
          bgRepeat={"no-repeat"}
          minH={"100vh"}
        >
          <Headline/>

          <Text w={1000} mx={'auto'} pl={160} mt={100} fontSize={18} fontWeight={400} lineHeight={'200%'}>
            Tokamak Bridge is a unified Dapp that supports both Swap and Bridge
            functionality. With it’s fun card game-like interface, fast
            transaction speeds and reward-full ecosystem, Tokamak Bridge is an
            all-in-one solution for cryptocurrency enthusiasts.
          </Text>

          <DataProvider/>
          <TokenCards/>
          <BridgeExplain/>
          <FeaturedTokens/>
          <PoolExplain/>
          <StartButtonGroup/>

        </Stack>
      </Box>
    </>
  );
}
